# Global rules
arrowParens: always
bracketSpacing: false
endOfLine: lf
printWidth: 100
quoteProps: consistent
singleQuote: true
tabWidth: 4
trailingComma: all

# Overrides
overrides:
  - files: '*.{html,json,md,yml}'
    options:
      tabWidth: 2
